repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        require_serial: true
        name: Coding style (Black)
        language_version: python3.8
        stages: [commit]
        exclude: ^legacy-backend.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        require_serial: true
        name: isort
        args: ["--profile", "black"]
        stages: [commit]
        exclude: ^legacy-backend.*$
