name: Pytest

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install libpcsclite-dev
        run: sudo apt-get install libpcsclite-dev
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -r requirements-dev.txt
      - run: pytest
